# Generated by Django 5.2.12 on 2026-03-24 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('warehouse_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Physical Hub', 'Physical Hub'), ('Mobile', 'Mobile')], default='Physical Hub', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouse_warehouse',
            },
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('location_number', models.CharField(blank=True, max_length=20)),
                ('location_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_locations', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'warehouse_sublocation',
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('count_date', models.DateField()),
                ('physical_count', models.DecimalField(decimal_places=2, max_digits=12)),
                ('system_count', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment_applied', models.BooleanField(default=False)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_counts', to='inventory.product')),
            ],
            options={
                'db_table': 'warehouse_inventorycount',
                'indexes': [models.Index(fields=['tenant_id', 'product_id'], name='warehouse_i_tenant__3b8933_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationAssignedInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='location_inventory', to='inventory.product')),
                ('sub_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_inventory', to='warehouse.sublocation')),
            ],
            options={
                'db_table': 'warehouse_locationassignedinventory',
                'indexes': [models.Index(fields=['tenant_id', 'sub_location_id'], name='warehouse_l_tenant__00c1fd_idx'), models.Index(fields=['tenant_id', 'product_id'], name='warehouse_l_tenant__a47beb_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transfer_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_transfers', to='inventory.product')),
                ('dest_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers_in', to='warehouse.sublocation')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers_out', to='warehouse.sublocation')),
            ],
            options={
                'db_table': 'warehouse_inventorytransfer',
                'indexes': [models.Index(fields=['tenant_id', 'product_id'], name='warehouse_i_tenant__a1f10c_idx'), models.Index(fields=['tenant_id', 'status'], name='warehouse_i_tenant__7644fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant_id', 'status'], name='warehouse_w_tenant__058da9_idx'),
        ),
        migrations.AddIndex(
            model_name='sublocation',
            index=models.Index(fields=['tenant_id', 'warehouse_id'], name='warehouse_s_tenant__bc97ba_idx'),
        ),
    ]
