# Generated by Django 5.0.1 on 2026-02-10 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        help_text="Type (e.g., Contract, Image). Controlled by Value List.",
                        max_length=50,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "stored_filename",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=255, unique=True
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        editable=False,
                        help_text="Full physical path or URL to the file.",
                        max_length=1024,
                    ),
                ),
                (
                    "created_from_table",
                    models.CharField(
                        editable=False,
                        help_text="Table name where this document originated (e.g., 'clients').",
                        max_length=50,
                    ),
                ),
                (
                    "created_from_id",
                    models.UUIDField(
                        editable=False,
                        help_text="ID of the record where this document originated.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="clients.client",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="documents.document",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="documents_d_created_3b0a51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["updated_at"], name="documents_d_updated_00a831_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_active"], name="documents_d_is_acti_e5a870_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentlink",
            index=models.Index(
                fields=["document"], name="documents_d_documen_469a4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentlink",
            index=models.Index(
                fields=["client"], name="documents_d_client__8faa95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentlink",
            index=models.Index(
                fields=["contact"], name="documents_d_contact_287efb_idx"
            ),
        ),
    ]
