# Generated by Django 5.0.1 on 2026-02-15 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("contacts", "0001_initial"),
        ("documents", "0001_initial"),
        ("products", "0003_product_date_started_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentlink",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_links",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="documentlink",
            index=models.Index(
                fields=["product"], name="documents_d_product_0c12d2_idx"
            ),
        ),
    ]
