# Generated by Django 6.0.3 on 2026-04-05 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "automation",
            "0002_wfinventory_wfsafetyform_wfstep_wfsteptodo_wftool_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_tenant_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EmployeeZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_employees",
                        to="automation.territoryzone",
                    ),
                ),
            ],
            options={
                "db_table": "users_employeezone",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "zone_id"],
                        name="users_emplo_tenant__e69818_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "employee_id"],
                        name="users_emplo_tenant__215b47_idx",
                    ),
                ],
                "unique_together": {("tenant_id", "zone", "employee")},
            },
        ),
    ]
