# Generated by Django 6.0.3 on 2026-04-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_customer_closed_reason"),
        ("users", "0005_user_username_login"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("tenant_id", "email")},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("tenant_id", "email"), ("tenant_id", "username")},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant_id", "username"], name="users_user_tenant__bb9518_idx"
            ),
        ),
    ]
