# Generated by Django 5.2.12 on 2026-03-24 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Push', 'Push'), ('In-App', 'In-App')], default='Email', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('subject', models.CharField(blank=True, help_text='Used for email; may include merge fields.', max_length=300)),
                ('body', models.TextField(help_text='Template body; supports merge fields with {{field_name}} syntax.')),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'automation_communicationtemplate',
                'indexes': [models.Index(fields=['tenant_id', 'channel'], name='automation__tenant__f38628_idx'), models.Index(fields=['tenant_id', 'status'], name='automation__tenant__e842e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('event_name', models.CharField(help_text='Internal event key, e.g. work_order.status_changed', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Optional filter conditions evaluated at trigger time.')),
            ],
            options={
                'db_table': 'automation_communicationtrigger',
                'indexes': [models.Index(fields=['tenant_id', 'event_name'], name='automation__tenant__8a08bb_idx'), models.Index(fields=['tenant_id', 'status'], name='automation__tenant__efcf20_idx')],
            },
        ),
        migrations.CreateModel(
            name='TriggerTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='Delay after trigger fires before sending.')),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_templates', to='automation.communicationtemplate')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_templates', to='automation.communicationtrigger')),
            ],
            options={
                'db_table': 'automation_triggertemplate',
            },
        ),
        migrations.CreateModel(
            name='TriggerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Skipped', 'Skipped')], default='Pending', max_length=10)),
                ('recipient', models.CharField(blank=True, help_text='Email address, phone number, or user ID.', max_length=300)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='Merge-field values used at send time.')),
                ('trigger_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.triggertemplate')),
            ],
            options={
                'db_table': 'automation_triggerlog',
            },
        ),
        migrations.AddIndex(
            model_name='triggertemplate',
            index=models.Index(fields=['tenant_id', 'trigger_id'], name='automation__tenant__f0aea5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='triggertemplate',
            unique_together={('trigger', 'template')},
        ),
        migrations.AddIndex(
            model_name='triggerlog',
            index=models.Index(fields=['tenant_id', 'status'], name='automation__tenant__773d96_idx'),
        ),
        migrations.AddIndex(
            model_name='triggerlog',
            index=models.Index(fields=['tenant_id', 'trigger_template_id'], name='automation__tenant__739cf8_idx'),
        ),
    ]
