# Generated by Django 5.0.1 on 2026-01-10 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attempted_username",
                    models.CharField(
                        blank=True,
                        help_text="Username entered at login (required when user is null)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "auth_result",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        help_text="Authentication result",
                        max_length=10,
                    ),
                ),
                (
                    "auth_failure_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for authentication failure",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Session start timestamp"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="Session end timestamp", null=True
                    ),
                ),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "Logout"),
                            ("timeout", "Timeout"),
                            ("admin_invalidate", "Admin Invalidate"),
                            ("auth_failure", "Auth Failure"),
                        ],
                        help_text="Reason session ended",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "client_info",
                    models.TextField(
                        blank=True,
                        help_text="User agent or client information",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of client", null=True
                    ),
                ),
                (
                    "user_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of user info at login (user_id, username, display_name, roles)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User (null if authentication failed)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_ts",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Event timestamp"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("create", "Create"), ("delete", "Delete")],
                        help_text="Type of event",
                        max_length=10,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Logical entity/table name (e.g., Client, Contact, Invoice)",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(help_text="UUID of the record created or deleted"),
                ),
                (
                    "reason_text",
                    models.TextField(
                        blank=True,
                        help_text="Reason for action (required for some delete operations)",
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short human-readable description",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session in which event occurred",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audit.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Transaction",
                "verbose_name_plural": "User Transactions",
                "ordering": ["-event_ts"],
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["user"], name="audit_sessi_user_id_ec919a_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["started_at"], name="audit_sessi_started_b3951b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["ended_at"], name="audit_sessi_ended_a_f128df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["auth_result"], name="audit_sessi_auth_re_9f1eef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertransaction",
            index=models.Index(
                fields=["session"], name="audit_usert_session_b6939e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertransaction",
            index=models.Index(fields=["user"], name="audit_usert_user_id_bf6139_idx"),
        ),
        migrations.AddIndex(
            model_name="usertransaction",
            index=models.Index(
                fields=["event_ts"], name="audit_usert_event_t_ae16bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertransaction",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="audit_usert_entity__d8e8da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usertransaction",
            index=models.Index(
                fields=["event_type"], name="audit_usert_event_t_f9cc20_idx"
            ),
        ),
    ]
