# Generated by Django 5.0.1 on 2026-01-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_alter_session_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertransaction",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("delete", "Delete"),
                    ("update", "Update"),
                ],
                help_text="Type of event",
                max_length=10,
            ),
        ),
    ]
