# Generated by Django 6.0.4 on 2026-05-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_workorder_total_amount_alter_workorder_actual_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="overdue_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voided_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="declined_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="invoiced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
