# Generated by Django 6.0.3 on 2026-05-11 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_quote_invoice_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="is_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="is_taxable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="is_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="is_taxable",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="InvoiceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("deposit_applied", models.BooleanField(default=False)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("customer_company_name", models.CharField(blank=True, max_length=200)),
                ("customer_display_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=80)),
                ("customer_address", models.TextField(blank=True)),
                ("lines_json", models.JSONField(blank=True, default=list)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="service.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "service_invoicesnapshot",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "invoice_id"],
                        name="service_inv_tenant__839e9c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuoteSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("customer_company_name", models.CharField(blank=True, max_length=200)),
                ("customer_display_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=80)),
                ("customer_address", models.TextField(blank=True)),
                ("lines_json", models.JSONField(blank=True, default=list)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="service.quote",
                    ),
                ),
            ],
            options={
                "db_table": "service_quotesnapshot",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "quote_id"],
                        name="service_quo_tenant__d8feb0_idx",
                    )
                ],
            },
        ),
    ]
