# Generated by Django 5.2.12 on 2026-03-24 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Ordered', 'Ordered'), ('Partially Received', 'Partially Received'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Draft', max_length=25)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ship_to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_pos', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'procurement_purchaseorder',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='po_lines', to='inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder')),
            ],
            options={
                'db_table': 'procurement_purchaseorderline',
            },
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivings', to='warehouse.sublocation')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receivings', to='procurement.purchaseorderline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receivings', to='inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receivings', to='procurement.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_receiving',
            },
        ),
        migrations.CreateModel(
            name='LotInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lot_info', to='inventory.product')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_info', to='procurement.receiving')),
            ],
            options={
                'db_table': 'procurement_lotinfo',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('requisition_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Converted', 'Converted')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='procurement.purchaseorder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_requisition',
            },
        ),
        migrations.CreateModel(
            name='RequisitionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requisition_lines', to='inventory.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.requisition')),
            ],
            options={
                'db_table': 'procurement_requisitionline',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('vendor_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'procurement_vendor',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='procurement_tenant__dc4607_idx')],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_orders', to='procurement.vendor'),
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Voided', 'Voided')], default='Draft', max_length=20)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='procurement.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bills', to='procurement.vendor')),
            ],
            options={
                'db_table': 'procurement_vendorbill',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['tenant_id', 'purchase_order_id'], name='procurement_tenant__8d9c62_idx'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['tenant_id', 'purchase_order_id'], name='procurement_tenant__d6d1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='lotinfo',
            index=models.Index(fields=['tenant_id', 'product_id'], name='procurement_tenant__98666b_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['tenant_id', 'status'], name='procurement_tenant__05e58f_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionline',
            index=models.Index(fields=['tenant_id', 'requisition_id'], name='procurement_tenant__8f79b8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant_id', 'status'], name='procurement_tenant__db6b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant_id', 'vendor_id'], name='procurement_tenant__02cb89_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['tenant_id', 'vendor_id'], name='procurement_tenant__b1501c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['tenant_id', 'status'], name='procurement_tenant__9ab0e4_idx'),
        ),
    ]
