# Generated by Django 6.0.4 on 2026-05-03

import config.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_vendor_billing_to_account(apps, schema_editor):
    """Copy each Vendor.payment_terms to a new VendorAccount row."""
    Vendor = apps.get_model("procurement", "Vendor")
    VendorAccount = apps.get_model("procurement", "VendorAccount")
    for v in Vendor.objects.all():
        VendorAccount.objects.create(
            tenant_id=v.tenant_id,
            vendor=v,
            payment_terms=v.payment_terms,
            created_by=v.created_by,
        )


def reverse_copy_account_to_vendor(apps, schema_editor):
    VendorAccount = apps.get_model("procurement", "VendorAccount")
    for a in VendorAccount.objects.select_related("vendor").all():
        v = a.vendor
        v.payment_terms = a.payment_terms
        v.save(update_fields=["payment_terms"])


def encrypt_existing_tax_ids(apps, schema_editor):
    """Encrypt plaintext Vendor.tax_id values in place. Uses raw SQL because
    the historical model now defines tax_id as EncryptedCharField, whose
    from_db_value would fail trying to decrypt the existing plaintext."""
    from config.encryption import encrypt
    with schema_editor.connection.cursor() as cur:
        cur.execute(
            "SELECT id, tax_id FROM procurement_vendor "
            "WHERE tax_id IS NOT NULL AND tax_id <> ''"
        )
        rows = cur.fetchall()
        for row_id, plaintext in rows:
            if plaintext.startswith("v1:"):
                continue  # idempotent — already encrypted
            cur.execute(
                "UPDATE procurement_vendor SET tax_id = %s WHERE id = %s",
                [encrypt(plaintext), str(row_id)],
            )


def decrypt_existing_tax_ids(apps, schema_editor):
    from config.encryption import decrypt
    with schema_editor.connection.cursor() as cur:
        cur.execute("SELECT id, tax_id FROM procurement_vendor WHERE tax_id LIKE 'v1:%%'")
        rows = cur.fetchall()
        for row_id, ciphertext in rows:
            cur.execute(
                "UPDATE procurement_vendor SET tax_id = %s WHERE id = %s",
                [decrypt(ciphertext), str(row_id)],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0002_alter_lotinfo_product_and_more"),
    ]

    operations = [
        # 1. Create VendorAccount table.
        migrations.CreateModel(
            name="VendorAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("payment_terms", models.CharField(blank=True, max_length=50)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "credit_status",
                    models.CharField(
                        choices=[("Good", "Good"), ("Fair", "Fair"), ("Poor", "Poor")],
                        default="Good",
                        max_length=10,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("tax_exempt", models.BooleanField(default=False)),
                ("pricing_tier", models.CharField(blank=True, max_length=50)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("po_required", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_vendoraccount",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "credit_status"],
                        name="procurement_tenant__2fc89c_idx",
                    )
                ],
            },
        ),
        # 2. Copy existing Vendor.payment_terms into new VendorAccount rows.
        migrations.RunPython(
            copy_vendor_billing_to_account,
            reverse_copy_account_to_vendor,
        ),
        # 3. Drop the moved field.
        migrations.RemoveField(
            model_name="vendor",
            name="payment_terms",
        ),
        # 4. Switch tax_id storage to TEXT-backed EncryptedCharField. The
        # column changes type but data is still plaintext until step 5.
        migrations.AlterField(
            model_name="vendor",
            name="tax_id",
            field=config.fields.EncryptedCharField(blank=True, max_length=50),
        ),
        # 5. Encrypt the existing plaintext tax_ids in place.
        migrations.RunPython(
            encrypt_existing_tax_ids,
            decrypt_existing_tax_ids,
        ),
    ]
