# Generated by Django 5.0.1 on 2026-02-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Product category (e.g. Electronics, Furniture)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Unit price",
                max_digits=10,
                null=True,
            ),
        ),
    ]
