# Generated by Django 5.0.1 on 2026-02-15 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_category_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_started",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date the product was started/introduced.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Product image", null=True, upload_to="products/"
            ),
        ),
    ]
