# Generated by Django 6.0.4 on 2026-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffuser",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
    ]
