# Generated by Django 6.0.3 on 2026-04-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_system_user_is_superuser_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffuser",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Optional short login handle (alternative to email).",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
    ]
