# Generated by Django 5.0.1 on 2026-01-27 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_left",
            field=models.DateField(
                blank=True,
                help_text="Date employee left the organization (if applicable)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                help_text="Gender",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Administrative notes about this user"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Primary phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="position",
            field=models.CharField(
                blank=True, help_text="Job title or position", max_length=200
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["position"], name="identity_us_positio_0d1769_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["date_left"], name="identity_us_date_le_5ed5a5_idx"
            ),
        ),
    ]
