# Generated by Django 6.0.3 on 2026-04-05 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_inventoryitem_and_more"),
        ("users", "0002_user_is_tenant_admin_employeezone"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorycount",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inventory_counts",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransfer",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inventory_transfers",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="locationassignedinventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="location_inventory",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="users.department",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "warehouse_location",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "department_id"],
                        name="warehouse_l_tenant__69a2f5_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "warehouse_id"],
                        name="warehouse_l_tenant__abb8d6_idx",
                    ),
                ],
            },
        ),
    ]
