# Generated by Django 6.0.3 on 2026-04-05 14:43

import django.db.models.deletion
import lifecycle.mixins
import numbering.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_inventoryitem_and_more"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotinfo",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lot_info",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="po_lines",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="receivings",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="requisitionline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="requisition_lines",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Do Not Use", "Do Not Use"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RMA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("rma_number", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Initiated", "Initiated"),
                            ("Shipped", "Shipped"),
                            ("Received by Vendor", "Received by Vendor"),
                            ("Credited", "Credited"),
                            ("Closed", "Closed"),
                            ("Denied", "Denied"),
                        ],
                        default="Initiated",
                        max_length=25,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Defective", "Defective"),
                            ("Wrong Item", "Wrong Item"),
                            ("Damaged", "Damaged"),
                            ("Overstock", "Overstock"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "po_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rmas",
                        to="procurement.purchaseorderline",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rmas",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rmas",
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_rma",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="procurement_tenant__21741e_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "vendor_id"],
                        name="procurement_tenant__ba88fb_idx",
                    ),
                ],
            },
            bases=(
                models.Model,
                numbering.mixins.NumberingMixin,
                lifecycle.mixins.LifecycleMixin,
            ),
        ),
    ]
