# Generated by Django 6.0.3 on 2026-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="closed_reason",
            field=models.TextField(blank=True),
        ),
    ]
