# Generated by Django 6.0.3 on 2026-04-05 20:49

import config.base_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("automation", "0003_wfinventory_product_wfsafetyform_safety_form_and_more"),
        ("crm", "0004_customer_closed_reason"),
        ("fleet", "0003_alter_vehicleinventory_product"),
        ("maintenance", "0002_agreement_agreement_number_and_more"),
        ("procurement", "0002_alter_lotinfo_product_and_more"),
        ("service", "0003_workorder_total_amount_alter_workorder_actual_hours"),
        ("tasks", "0001_initial"),
        ("warehouse", "0002_alter_inventorycount_product_and_more"),
        ("workforce", "0002_workgroup_work_group_number_skill_employeeskill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("internal_note", "Internal Note"),
                            ("call", "Call"),
                            ("email", "Email"),
                            ("site_visit", "Site Visit"),
                            ("customer_comment", "Customer Comment"),
                            ("reminder", "Reminder"),
                        ],
                        default="internal_note",
                        max_length=50,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="maintenance.asset",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="crm.contact",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="crm.customer",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="automation.equipment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="service.invoice",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="crm.lead",
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="service.ledger",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="crm.opportunity",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="service.payments",
                    ),
                ),
                (
                    "prev_maint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="maintenance.preventativemaintenance",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="service.quote",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="procurement.requisition",
                    ),
                ),
                (
                    "rma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="procurement.rma",
                    ),
                ),
                (
                    "safety_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="automation.safetyform",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="service.servicerequest",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="fleet.vehicle",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="procurement.vendor",
                    ),
                ),
                (
                    "vendor_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="procurement.vendorbill",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "work_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="workforce.workgroup",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="service.workorder",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_records",
                        to="automation.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "notes_note",
                "indexes": [
                    models.Index(
                        condition=models.Q(("customer_id__isnull", False)),
                        fields=["tenant_id", "customer_id"],
                        name="note_customer_idx",
                    ),
                    models.Index(
                        condition=models.Q(("contact_id__isnull", False)),
                        fields=["tenant_id", "contact_id"],
                        name="note_contact_idx",
                    ),
                    models.Index(
                        condition=models.Q(("lead_id__isnull", False)),
                        fields=["tenant_id", "lead_id"],
                        name="note_lead_idx",
                    ),
                    models.Index(
                        condition=models.Q(("opportunity_id__isnull", False)),
                        fields=["tenant_id", "opportunity_id"],
                        name="note_opportunity_idx",
                    ),
                    models.Index(
                        condition=models.Q(("quote_id__isnull", False)),
                        fields=["tenant_id", "quote_id"],
                        name="note_quote_idx",
                    ),
                    models.Index(
                        condition=models.Q(("invoice_id__isnull", False)),
                        fields=["tenant_id", "invoice_id"],
                        name="note_invoice_idx",
                    ),
                    models.Index(
                        condition=models.Q(("work_order_id__isnull", False)),
                        fields=["tenant_id", "work_order_id"],
                        name="note_work_order_idx",
                    ),
                    models.Index(
                        condition=models.Q(("asset_id__isnull", False)),
                        fields=["tenant_id", "asset_id"],
                        name="note_asset_idx",
                    ),
                    models.Index(
                        condition=models.Q(("service_request_id__isnull", False)),
                        fields=["tenant_id", "service_request_id"],
                        name="note_service_request_idx",
                    ),
                    models.Index(
                        condition=models.Q(("prev_maint_id__isnull", False)),
                        fields=["tenant_id", "prev_maint_id"],
                        name="note_prev_maint_idx",
                    ),
                    models.Index(
                        condition=models.Q(("payment_id__isnull", False)),
                        fields=["tenant_id", "payment_id"],
                        name="note_payment_idx",
                    ),
                    models.Index(
                        condition=models.Q(("user_id__isnull", False)),
                        fields=["tenant_id", "user_id"],
                        name="note_user_idx",
                    ),
                    models.Index(
                        condition=models.Q(("vendor_id__isnull", False)),
                        fields=["tenant_id", "vendor_id"],
                        name="note_vendor_idx",
                    ),
                    models.Index(
                        condition=models.Q(("purchase_order_id__isnull", False)),
                        fields=["tenant_id", "purchase_order_id"],
                        name="note_purchase_order_idx",
                    ),
                    models.Index(
                        condition=models.Q(("work_group_id__isnull", False)),
                        fields=["tenant_id", "work_group_id"],
                        name="note_work_group_idx",
                    ),
                    models.Index(
                        condition=models.Q(("task_id__isnull", False)),
                        fields=["tenant_id", "task_id"],
                        name="note_task_idx",
                    ),
                    models.Index(
                        condition=models.Q(("vehicle_id__isnull", False)),
                        fields=["tenant_id", "vehicle_id"],
                        name="note_vehicle_idx",
                    ),
                    models.Index(
                        condition=models.Q(("warehouse_id__isnull", False)),
                        fields=["tenant_id", "warehouse_id"],
                        name="note_warehouse_idx",
                    ),
                    models.Index(
                        condition=models.Q(("ledger_id__isnull", False)),
                        fields=["tenant_id", "ledger_id"],
                        name="note_ledger_idx",
                    ),
                    models.Index(
                        condition=models.Q(("requisition_id__isnull", False)),
                        fields=["tenant_id", "requisition_id"],
                        name="note_requisition_idx",
                    ),
                    models.Index(
                        condition=models.Q(("workflow_id__isnull", False)),
                        fields=["tenant_id", "workflow_id"],
                        name="note_workflow_idx",
                    ),
                    models.Index(
                        condition=models.Q(("rma_id__isnull", False)),
                        fields=["tenant_id", "rma_id"],
                        name="note_rma_idx",
                    ),
                    models.Index(
                        condition=models.Q(("equipment_id__isnull", False)),
                        fields=["tenant_id", "equipment_id"],
                        name="note_equipment_idx",
                    ),
                    models.Index(
                        condition=models.Q(("safety_form_id__isnull", False)),
                        fields=["tenant_id", "safety_form_id"],
                        name="note_safety_form_idx",
                    ),
                    models.Index(
                        condition=models.Q(("vendor_bill_id__isnull", False)),
                        fields=["tenant_id", "vendor_bill_id"],
                        name="note_vendor_bill_idx",
                    ),
                ],
            },
            bases=(models.Model, config.base_models.ExclusiveArcMixin),
        ),
    ]
