# Generated by Django 5.2.12 on 2026-03-24 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WGDivision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'workforce_wgdivision',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='workforce_w_tenant__2828eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_groups', to='workforce.wgdivision')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_work_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workforce_workgroup',
            },
        ),
        migrations.CreateModel(
            name='WGTRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='workforce.workgroup')),
            ],
            options={
                'db_table': 'workforce_wgtrole',
            },
        ),
        migrations.CreateModel(
            name='WorkGroupAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_group_assignments', to='maintenance.asset')),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='workforce.workgroup')),
            ],
            options={
                'db_table': 'workforce_workgroupasset',
            },
        ),
        migrations.CreateModel(
            name='WorkGroupTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='workforce.wgtrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='workforce.workgroup')),
            ],
            options={
                'db_table': 'workforce_workgroupteam',
            },
        ),
        migrations.AddIndex(
            model_name='workgroup',
            index=models.Index(fields=['tenant_id', 'status'], name='workforce_w_tenant__50dc80_idx'),
        ),
        migrations.AddIndex(
            model_name='workgroup',
            index=models.Index(fields=['tenant_id', 'division_id'], name='workforce_w_tenant__eaca14_idx'),
        ),
        migrations.AddIndex(
            model_name='wgtrole',
            index=models.Index(fields=['tenant_id', 'work_group_id'], name='workforce_w_tenant__e8bbde_idx'),
        ),
        migrations.AddIndex(
            model_name='workgroupasset',
            index=models.Index(fields=['tenant_id', 'work_group_id'], name='workforce_w_tenant__cb21c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workgroupasset',
            unique_together={('work_group', 'asset')},
        ),
        migrations.AddIndex(
            model_name='workgroupteam',
            index=models.Index(fields=['tenant_id', 'work_group_id'], name='workforce_w_tenant__67be60_idx'),
        ),
        migrations.AddIndex(
            model_name='workgroupteam',
            index=models.Index(fields=['tenant_id', 'user_id'], name='workforce_w_tenant__791b0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workgroupteam',
            unique_together={('work_group', 'user')},
        ),
    ]
