# Generated by Django 6.0.3 on 2026-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="agreement_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="preventativemaintenance",
            name="pm_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
