# Generated by Django 6.0.3 on 2026-04-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "automation",
            "0002_wfinventory_wfsafetyform_wfstep_wfsteptodo_wftool_and_more",
        ),
        ("documents", "0001_initial"),
        ("inventory", "0003_inventoryitem_and_more"),
        ("service", "0002_invoice_deposit_amount_invoice_deposit_applied_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wfinventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="workflow_usage",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="wfsafetyform",
            name="safety_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_usage",
                to="automation.safetyform",
            ),
        ),
        migrations.AddField(
            model_name="wfsteptodo",
            name="wf_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="automation.wfstep",
            ),
        ),
        migrations.AddField(
            model_name="wftool",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="workflow_usage",
                to="automation.equipment",
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["tenant_id", "status"], name="automation__tenant__164c7b_idx"
            ),
        ),
        migrations.AddField(
            model_name="wftool",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tools",
                to="automation.workflow",
            ),
        ),
        migrations.AddField(
            model_name="wfstep",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="automation.workflow",
            ),
        ),
        migrations.AddField(
            model_name="wfsafetyform",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_forms",
                to="automation.workflow",
            ),
        ),
        migrations.AddField(
            model_name="wfinventory",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="automation.workflow",
            ),
        ),
        migrations.AddField(
            model_name="wosfanswer",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="safety_form_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wosfanswer",
            name="safety_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="automation.safetyform",
            ),
        ),
        migrations.AddField(
            model_name="wosfanswer",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_form_answers",
                to="service.workorder",
            ),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(
                fields=["tenant_id", "employee_id"],
                name="automation__tenant__f73760_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(
                fields=["tenant_id", "status"], name="automation__tenant__419a85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeepurchase",
            index=models.Index(
                fields=["tenant_id", "employee_id"],
                name="automation__tenant__154b78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeepurchase",
            index=models.Index(
                fields=["tenant_id", "status"], name="automation__tenant__9b3337_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeepurchase",
            index=models.Index(
                fields=["tenant_id", "credit_card_id"],
                name="automation__tenant__a28822_idx",
            ),
        ),
        migrations.AddField(
            model_name="employeepurchase",
            name="receipt_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_receipts",
                to="documents.document",
            ),
        ),
        migrations.AddIndex(
            model_name="checkinout",
            index=models.Index(
                fields=["tenant_id", "equipment_id"],
                name="automation__tenant__eff2e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkinout",
            index=models.Index(
                fields=["tenant_id", "employee_id"],
                name="automation__tenant__805a11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["tenant_id", "project_id"],
                name="automation__tenant__470651_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["tenant_id", "status"], name="automation__tenant__cda9f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestonetask",
            index=models.Index(
                fields=["tenant_id", "milestone_id"],
                name="automation__tenant__03fa01_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="milestonetask",
            unique_together={("tenant_id", "milestone", "task")},
        ),
        migrations.AddIndex(
            model_name="portfoliomember",
            index=models.Index(
                fields=["tenant_id", "portfolio_id"],
                name="automation__tenant__a8f69a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfoliomember",
            unique_together={("tenant_id", "portfolio", "employee")},
        ),
        migrations.AddIndex(
            model_name="portfolioproject",
            index=models.Index(
                fields=["tenant_id", "portfolio_id"],
                name="automation__tenant__fe1be5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfolioproject",
            unique_together={("tenant_id", "portfolio", "project")},
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["tenant_id", "project_id"],
                name="automation__tenant__d1e5e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["tenant_id", "status"], name="automation__tenant__64783c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprintmember",
            index=models.Index(
                fields=["tenant_id", "sprint_id"], name="automation__tenant__c0779a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sprintmember",
            unique_together={("tenant_id", "sprint", "employee")},
        ),
        migrations.AddIndex(
            model_name="sprinttask",
            index=models.Index(
                fields=["tenant_id", "sprint_id"], name="automation__tenant__7f6499_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sprinttask",
            unique_together={("tenant_id", "sprint", "task")},
        ),
        migrations.AddIndex(
            model_name="territoryzone",
            index=models.Index(
                fields=["tenant_id", "status"], name="automation__tenant__155112_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wfsteptodo",
            index=models.Index(
                fields=["tenant_id", "wf_step_id"],
                name="automation__tenant__1134c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wftool",
            index=models.Index(
                fields=["tenant_id", "workflow_id"],
                name="automation__tenant__47c1b3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wftool",
            unique_together={("tenant_id", "workflow", "equipment")},
        ),
        migrations.AddIndex(
            model_name="wfstep",
            index=models.Index(
                fields=["tenant_id", "workflow_id"],
                name="automation__tenant__2f6673_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wfsafetyform",
            index=models.Index(
                fields=["tenant_id", "workflow_id"],
                name="automation__tenant__de5230_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wfsafetyform",
            unique_together={("tenant_id", "workflow", "safety_form")},
        ),
        migrations.AddIndex(
            model_name="wfinventory",
            index=models.Index(
                fields=["tenant_id", "workflow_id"],
                name="automation__tenant__403ad5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wfinventory",
            unique_together={("tenant_id", "workflow", "product")},
        ),
        migrations.AddIndex(
            model_name="wosfanswer",
            index=models.Index(
                fields=["tenant_id", "work_order_id"],
                name="automation__tenant__218815_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wosfanswer",
            index=models.Index(
                fields=["tenant_id", "safety_form_id"],
                name="automation__tenant__140b4c_idx",
            ),
        ),
    ]
