# Generated by Django 6.0.3 on 2026-04-05 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LifecycleStateDef",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=50)),
                ("state_name", models.CharField(max_length=50)),
                ("state_label", models.CharField(max_length=100)),
                (
                    "state_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("locked", "Locked"),
                            ("final", "Final"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "lifecycle_lifecyclestatedef",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type"],
                        name="lifecycle_l_tenant__7454f0_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "entity_type", "is_default"],
                        name="lifecycle_l_tenant__a9ccae_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "entity_type", "state_name"),
                        name="unique_state_per_entity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LifecycleTransitionAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.UUIDField()),
                ("user_display", models.CharField(max_length=200)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField()),
                ("from_state", models.CharField(max_length=50)),
                ("to_state", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True)),
                ("is_override", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "lifecycle_lifecycletransitionaudit",
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type", "entity_id"],
                        name="lifecycle_l_tenant__a2a1cd_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "entity_type"],
                        name="lifecycle_l_tenant__1640ff_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "timestamp"],
                        name="lifecycle_l_tenant__242e9a_idx",
                    ),
                    models.Index(
                        fields=["user_id"], name="lifecycle_l_user_id_1f4918_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LifecycleTransitionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=50)),
                ("from_state", models.CharField(max_length=50)),
                ("to_state", models.CharField(max_length=50)),
                ("required_role", models.CharField(blank=True, max_length=100)),
                ("requires_reason", models.BooleanField(default=False)),
                ("is_admin_override", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "lifecycle_lifecycletransitionrule",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type"],
                        name="lifecycle_l_tenant__e9a5d2_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "entity_type", "from_state"],
                        name="lifecycle_l_tenant__7b66bc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "entity_type", "from_state", "to_state"),
                        name="unique_transition_per_entity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_state", models.F("to_state")), _negated=True
                        ),
                        name="from_state_ne_to_state",
                    ),
                ],
            },
        ),
    ]
