# Generated by Django 6.0.3 on 2026-04-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionlog",
            name="permission_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="tenantpreference",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
