# Generated by Django 6.0.3 on 2026-04-05 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workforce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="work_group_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Certification", "Certification"),
                            ("License", "License"),
                            ("Training", "Training"),
                            ("Competency", "Competency"),
                        ],
                        default="Competency",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "workforce_skill",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="workforce_s_tenant__412a67_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "category"],
                        name="workforce_s_tenant__f1da98_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("date_earned", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Expired", "Expired")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_skills",
                        to="workforce.skill",
                    ),
                ),
            ],
            options={
                "db_table": "workforce_employeeskill",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "employee_id"],
                        name="workforce_e_tenant__30718f_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "skill_id"],
                        name="workforce_e_tenant__d9ecbf_idx",
                    ),
                ],
                "unique_together": {("tenant_id", "employee", "skill")},
            },
        ),
    ]
