# Generated by Django 6.0.3 on 2026-04-05 20:49

import config.base_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("automation", "0002_wfinventory_wfsafetyform_wfstep_wfsteptodo_wftool_and_more"),
        ("crm", "0004_customer_closed_reason"),
        ("fleet", "0003_alter_vehicleinventory_product"),
        ("maintenance", "0002_agreement_agreement_number_and_more"),
        ("procurement", "0002_alter_lotinfo_product_and_more"),
        ("service", "0003_workorder_total_amount_alter_workorder_actual_hours"),
        ("tasks", "0001_initial"),
        ("warehouse", "0002_alter_inventorycount_product_and_more"),
        ("workforce", "0002_workgroup_work_group_number_skill_employeeskill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_key", models.CharField(max_length=500)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("sha256_hash", models.CharField(blank=True, max_length=64)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="maintenance.asset",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="crm.contact",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="crm.customer",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="automation.equipment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="service.invoice",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="crm.lead",
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="service.ledger",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="crm.opportunity",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="service.payments",
                    ),
                ),
                (
                    "prev_maint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="maintenance.preventativemaintenance",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="service.quote",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="procurement.requisition",
                    ),
                ),
                (
                    "rma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="procurement.rma",
                    ),
                ),
                (
                    "safety_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="automation.safetyform",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="service.servicerequest",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="fleet.vehicle",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="procurement.vendor",
                    ),
                ),
                (
                    "vendor_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="procurement.vendorbill",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "work_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="workforce.workgroup",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="service.workorder",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_records",
                        to="automation.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "documents_document",
            },
            bases=(models.Model, config.base_models.ExclusiveArcMixin),
        ),
        migrations.CreateModel(
            name="FileDownloadLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.UUIDField()),
                ("user_display", models.CharField(max_length=200)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="download_logs",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "documents_file_download_log",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="FileUploadLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField()),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_logs",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "documents_file_upload_log",
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("customer_id__isnull", False)),
                fields=["tenant_id", "customer_id"],
                name="doc_customer_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("contact_id__isnull", False)),
                fields=["tenant_id", "contact_id"],
                name="doc_contact_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("lead_id__isnull", False)),
                fields=["tenant_id", "lead_id"],
                name="doc_lead_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("opportunity_id__isnull", False)),
                fields=["tenant_id", "opportunity_id"],
                name="doc_opportunity_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("quote_id__isnull", False)),
                fields=["tenant_id", "quote_id"],
                name="doc_quote_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("invoice_id__isnull", False)),
                fields=["tenant_id", "invoice_id"],
                name="doc_invoice_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("work_order_id__isnull", False)),
                fields=["tenant_id", "work_order_id"],
                name="doc_work_order_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("asset_id__isnull", False)),
                fields=["tenant_id", "asset_id"],
                name="doc_asset_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("service_request_id__isnull", False)),
                fields=["tenant_id", "service_request_id"],
                name="doc_service_request_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("prev_maint_id__isnull", False)),
                fields=["tenant_id", "prev_maint_id"],
                name="doc_prev_maint_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("payment_id__isnull", False)),
                fields=["tenant_id", "payment_id"],
                name="doc_payment_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("user_id__isnull", False)),
                fields=["tenant_id", "user_id"],
                name="doc_user_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("vendor_id__isnull", False)),
                fields=["tenant_id", "vendor_id"],
                name="doc_vendor_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("purchase_order_id__isnull", False)),
                fields=["tenant_id", "purchase_order_id"],
                name="doc_purchase_order_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("work_group_id__isnull", False)),
                fields=["tenant_id", "work_group_id"],
                name="doc_work_group_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("task_id__isnull", False)),
                fields=["tenant_id", "task_id"],
                name="doc_task_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("vehicle_id__isnull", False)),
                fields=["tenant_id", "vehicle_id"],
                name="doc_vehicle_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("warehouse_id__isnull", False)),
                fields=["tenant_id", "warehouse_id"],
                name="doc_warehouse_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("ledger_id__isnull", False)),
                fields=["tenant_id", "ledger_id"],
                name="doc_ledger_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("requisition_id__isnull", False)),
                fields=["tenant_id", "requisition_id"],
                name="doc_requisition_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("workflow_id__isnull", False)),
                fields=["tenant_id", "workflow_id"],
                name="doc_workflow_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("rma_id__isnull", False)),
                fields=["tenant_id", "rma_id"],
                name="doc_rma_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("equipment_id__isnull", False)),
                fields=["tenant_id", "equipment_id"],
                name="doc_equipment_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("safety_form_id__isnull", False)),
                fields=["tenant_id", "safety_form_id"],
                name="doc_safety_form_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("vendor_bill_id__isnull", False)),
                fields=["tenant_id", "vendor_bill_id"],
                name="doc_vendor_bill_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filedownloadlog",
            index=models.Index(
                fields=["tenant_id", "document_id"],
                name="documents_f_tenant__e67cb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filedownloadlog",
            index=models.Index(
                fields=["tenant_id", "user_id"], name="documents_f_tenant__1081c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filedownloadlog",
            index=models.Index(
                fields=["timestamp"], name="documents_f_timesta_382b5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadlog",
            index=models.Index(
                fields=["tenant_id", "entity_type", "entity_id"],
                name="documents_f_tenant__e3f504_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadlog",
            index=models.Index(
                fields=["tenant_id", "status"], name="documents_f_tenant__ac902b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadlog",
            index=models.Index(
                fields=["created_on"], name="documents_f_created_728c7e_idx"
            ),
        ),
    ]
