# Generated by Django 5.0.1 on 2026-01-11 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifecycleTransitionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the transition occurred"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity that changed state", max_length=50
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(help_text="ID of the entity that changed state"),
                ),
                (
                    "from_state",
                    models.CharField(
                        help_text="Previous lifecycle state", max_length=50
                    ),
                ),
                (
                    "to_state",
                    models.CharField(help_text="New lifecycle state", max_length=50),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for state transition (if provided)",
                    ),
                ),
                (
                    "is_override",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this was an administrative override transition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this transition",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="LifecycleTransitionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type (e.g., 'order')", max_length=50
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        help_text="Starting state for this transition", max_length=50
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        help_text="Destination state for this transition", max_length=50
                    ),
                ),
                (
                    "required_permission",
                    models.CharField(
                        blank=True,
                        help_text="Permission required for this transition (e.g., 'approve')",
                        max_length=100,
                    ),
                ),
                (
                    "requires_reason",
                    models.BooleanField(
                        default=False,
                        help_text="Whether transition must include a reason text",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Documentation about when/why this transition occurs",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LifecycleStateDef",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type this state applies to (e.g., 'order')",
                        max_length=50,
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        help_text="Machine-readable state name (e.g., 'draft', 'approved')",
                        max_length=50,
                    ),
                ),
                (
                    "state_label",
                    models.CharField(
                        help_text="Human-friendly display label (e.g., 'Draft')",
                        max_length=100,
                    ),
                ),
                (
                    "state_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal State"),
                            ("locked", "Locked State"),
                            ("final", "Final State"),
                        ],
                        default="normal",
                        help_text="Classification: normal, locked (no edits), or final (no transitions)",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default initial state for new records"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Documentation about this state"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type"], name="lifecycle_l_entity__3dfde0_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "is_default"],
                        name="lifecycle_l_entity__225773_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="lifecyclestatedef",
            constraint=models.UniqueConstraint(
                fields=("entity_type", "state_name"), name="unique_entity_state"
            ),
        ),
        migrations.AddIndex(
            model_name="lifecycletransitionaudit",
            index=models.Index(
                fields=["entity_type"], name="lifecycle_l_entity__0d638d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lifecycletransitionaudit",
            index=models.Index(
                fields=["entity_id"], name="lifecycle_l_entity__0e0459_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lifecycletransitionaudit",
            index=models.Index(
                fields=["timestamp"], name="lifecycle_l_timesta_568559_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lifecycletransitionaudit",
            index=models.Index(fields=["user"], name="lifecycle_l_user_id_1f4918_idx"),
        ),
        migrations.AddIndex(
            model_name="lifecycletransitionrule",
            index=models.Index(
                fields=["entity_type"], name="lifecycle_l_entity__066f02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lifecycletransitionrule",
            index=models.Index(
                fields=["entity_type", "from_state"],
                name="lifecycle_l_entity__96b405_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="lifecycletransitionrule",
            constraint=models.UniqueConstraint(
                fields=("entity_type", "from_state", "to_state"),
                name="unique_entity_transition",
            ),
        ),
    ]
