"""Field-level encryption wrapper.

Single point of control for symmetric encryption of model fields. Application
code must NOT import nacl directly — go through encrypt() / decrypt() so the
underlying algorithm can be swapped (or rotated) without touching call sites.

Ciphertext format
-----------------
All ciphertext is stored as ``"v1:<base64url-of-nonce-and-box>"``.

* ``v1`` = libsodium SecretBox (XSalsa20-Poly1305) with a fresh random 24-byte
  nonce per encryption. The nonce is prepended to the ciphertext by
  ``SecretBox.encrypt()`` and parsed back out by ``SecretBox.decrypt()``.
* The version prefix exists so a future ``v2`` algorithm can be introduced
  alongside ``v1`` and a re-encryption pass run online without downtime.

Empty / None policy
-------------------
``encrypt('')`` returns ``''`` and ``decrypt('')`` returns ``''``. This keeps
``blank=True`` model fields working naturally — the empty marker isn't worth
a round-trip through the cipher.

Key
---
The 32-byte symmetric key is loaded from ``settings.FIELD_ENCRYPTION_KEY``,
which is in turn populated from the ``FIELD_ENCRYPTION_KEY`` environment
variable. The key is base64url-encoded (44 chars including padding).

In DEBUG mode, if the key is missing, a fresh one is generated and appended
to the ``.env`` file with a printed warning. In production, missing key
raises ``ImproperlyConfigured`` — operators must inject it from the
secrets vault.
"""

from __future__ import annotations

import base64
import os
from pathlib import Path

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from nacl.secret import SecretBox
from nacl.utils import random as nacl_random

_PREFIX_V1 = "v1:"
_KEY_BYTES = SecretBox.KEY_SIZE  # 32

_box_cache: SecretBox | None = None


def _generate_key_b64() -> str:
    """Generate a fresh 32-byte key, base64url-encoded for env storage."""
    return base64.urlsafe_b64encode(nacl_random(_KEY_BYTES)).decode("ascii")


def _ensure_dev_key(env_path: Path) -> str:
    """Append a freshly-generated FIELD_ENCRYPTION_KEY to .env in DEBUG mode."""
    key = _generate_key_b64()
    with env_path.open("a", encoding="utf-8") as fh:
        fh.write(
            "\n# Auto-generated by config/encryption.py for local dev only.\n"
            "# Do NOT use this key in staging or production.\n"
            f"FIELD_ENCRYPTION_KEY={key}\n"
        )
    return key


def _load_box() -> SecretBox:
    """Resolve the configured key into a SecretBox instance, cached process-wide."""
    global _box_cache
    if _box_cache is not None:
        return _box_cache

    raw_key_b64 = getattr(settings, "FIELD_ENCRYPTION_KEY", "") or ""

    if not raw_key_b64:
        if getattr(settings, "DEBUG", False):
            env_path = Path(settings.BASE_DIR) / ".env"
            if env_path.exists():
                raw_key_b64 = _ensure_dev_key(env_path)
                os.environ["FIELD_ENCRYPTION_KEY"] = raw_key_b64
                print(
                    "[encryption] FIELD_ENCRYPTION_KEY was missing; "
                    "generated a dev key and appended to .env. "
                    "Restart the process to pick it up cleanly."
                )
            else:
                raise ImproperlyConfigured(
                    "FIELD_ENCRYPTION_KEY is not set and no .env file exists "
                    f"at {env_path} to write a dev key into."
                )
        else:
            raise ImproperlyConfigured(
                "FIELD_ENCRYPTION_KEY environment variable is required in "
                "production. Inject it from the secrets vault."
            )

    try:
        key_bytes = base64.urlsafe_b64decode(raw_key_b64.encode("ascii"))
    except Exception as exc:
        raise ImproperlyConfigured(
            "FIELD_ENCRYPTION_KEY is not valid base64url."
        ) from exc

    if len(key_bytes) != _KEY_BYTES:
        raise ImproperlyConfigured(
            f"FIELD_ENCRYPTION_KEY decodes to {len(key_bytes)} bytes; "
            f"expected {_KEY_BYTES}."
        )

    _box_cache = SecretBox(key_bytes)
    return _box_cache


def encrypt(plaintext: str) -> str:
    """Encrypt a plaintext string. Empty in → empty out."""
    if plaintext is None or plaintext == "":
        return ""
    box = _load_box()
    ciphertext = box.encrypt(plaintext.encode("utf-8"))  # nonce prepended
    return _PREFIX_V1 + base64.urlsafe_b64encode(ciphertext).decode("ascii")


def decrypt(ciphertext: str) -> str:
    """Decrypt a ciphertext string previously produced by encrypt()."""
    if ciphertext is None or ciphertext == "":
        return ""
    if ciphertext.startswith(_PREFIX_V1):
        payload_b64 = ciphertext[len(_PREFIX_V1):]
        box = _load_box()
        try:
            payload = base64.urlsafe_b64decode(payload_b64.encode("ascii"))
            return box.decrypt(payload).decode("utf-8")
        except Exception as exc:
            raise ValueError("Failed to decrypt v1 ciphertext.") from exc
    raise ValueError(f"Unknown ciphertext version prefix in: {ciphertext[:8]!r}")


def reset_cache_for_tests() -> None:
    """Test helper — drop the cached SecretBox so a new key can be loaded."""
    global _box_cache
    _box_cache = None
