# Generated by Django 5.0.1 on 2026-01-11 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.CharField(max_length=1000)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["key"], name="app_shell_a_key_8e8ed4_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="NavItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=200)),
                (
                    "url_name",
                    models.CharField(help_text="Django URL name", max_length=200),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "section",
                    models.CharField(
                        default="main", help_text="Nav section grouping", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="app_shell.navitem",
                    ),
                ),
                (
                    "required_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Roles required to see this item (empty = visible to all)",
                        related_name="nav_items",
                        to="identity.role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["section", "parent__id", "order", "label"],
                "indexes": [
                    models.Index(
                        fields=["section", "order"],
                        name="app_shell_n_section_ccae29_idx",
                    ),
                    models.Index(
                        fields=["parent", "order"],
                        name="app_shell_n_parent__9166c7_idx",
                    ),
                ],
            },
        ),
    ]
