# Generated by Django 5.2.12 on 2026-03-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_products', to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='pricebookentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricebook_entries', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='kititem',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='kititem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='included_in_kits', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='invpricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_p_tenant__79df85_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'type'], name='inventory_p_tenant__ed1c40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricebookentry',
            unique_together={('tenant_id', 'pricebook', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='kititem',
            unique_together={('tenant_id', 'kit', 'product')},
        ),
        migrations.AddIndex(
            model_name='invpricehistory',
            index=models.Index(fields=['tenant_id', 'product_id'], name='inventory_i_tenant__201f12_idx'),
        ),
    ]
