# Generated by Django 6.0.3 on 2026-04-05 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0003_alter_vehicleinventory_product"),
        ("inventory", "0003_inventoryitem_and_more"),
        ("procurement", "0002_alter_lotinfo_product_and_more"),
        ("service", "0002_invoice_deposit_amount_invoice_deposit_applied_and_more"),
        ("warehouse", "0002_alter_inventorycount_product_and_more"),
    ]

    operations = [
        # Product was renamed to InventoryItem in 0003.
        # Keep this migration as a no-op to preserve dependency graph.
    ]
