# Generated by Django 5.2.12 on 2026-03-24 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('Service', 'Service'), ('Billing', 'Billing'), ('Mailing', 'Mailing'), ('Other', 'Other')], default='Service', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('street', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'crm_address',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('role_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Left', 'Left')], default='Active', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('left_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_contact',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('account_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], default='Residential', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('lead_source', models.CharField(blank=True, max_length=100)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('customer_since', models.DateField(blank=True, null=True)),
                ('hold_date', models.DateTimeField(blank=True, null=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_terms', models.CharField(blank=True, max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_status', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=10)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'crm_customer',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lead_number', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(blank=True, choices=[('Referral', 'Referral'), ('Website', 'Website'), ('Advertisement', 'Advertisement'), ('Trade Show', 'Trade Show'), ('Cold Call', 'Cold Call'), ('Other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'crm_lead',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('opportunity_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Won', 'Won'), ('Lost', 'Lost')], default='Open', max_length=10)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'crm_opportunity',
            },
        ),
        migrations.CreateModel(
            name='OpportunityContacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('role_in_opportunity', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'crm_opportunitycontacts',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'crm_person',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('phone_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Office', 'Office'), ('Home', 'Home'), ('Fax', 'Fax'), ('Other', 'Other')], default='Mobile', max_length=10)),
                ('number', models.CharField(max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('extension', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'crm_phone',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Email', 'Email'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Twitter/X', 'Twitter/X'), ('YouTube', 'YouTube'), ('Website', 'Website'), ('Other', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'crm_social',
            },
        ),
    ]
