# Generated by Django 6.0.4 on 2026-05-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0005_add_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="inactive_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="inactive_reason",
            field=models.TextField(blank=True),
        ),
    ]
