# Generated by Django 6.0.4 on 2026-05-03 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0010_contact_expansion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="For B2B leads — the company they represent.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_contacted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Lead quality score, 0–100.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="lost_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="lost_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="next_followup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="qualified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="actual_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Realized value when Won. Defaults to estimated_value if unset.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="competitor",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="lost_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="lost_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="next_step",
            field=models.CharField(
                blank=True,
                help_text="The next action to advance this opportunity.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="probability",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Conversion likelihood, 0–100.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="won_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant_id", "status"], name="crm_lead_tenant__3e1c47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant_id", "assigned_to_id"],
                name="crm_lead_tenant__d99927_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["tenant_id", "status"], name="crm_opportu_tenant__d9c0e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["tenant_id", "assigned_to_id"],
                name="crm_opportu_tenant__4bd88f_idx",
            ),
        ),
    ]
