# Generated by Django 6.0.4 on 2026-05-03

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_customer_billing_to_account(apps, schema_editor):
    Customer = apps.get_model("crm", "Customer")
    Account = apps.get_model("crm", "Account")
    for c in Customer.objects.all():
        Account.objects.create(
            tenant_id=c.tenant_id,
            customer=c,
            account_terms=c.account_terms,
            credit_limit=c.credit_limit,
            credit_status=c.credit_status,
            tax_rate=c.tax_rate,
            tax_exempt=c.tax_exempt,
            created_by=c.created_by,
        )


def reverse_copy_account_to_customer(apps, schema_editor):
    Account = apps.get_model("crm", "Account")
    for a in Account.objects.select_related("customer").all():
        c = a.customer
        c.account_terms = a.account_terms
        c.credit_limit = a.credit_limit
        c.credit_status = a.credit_status
        c.tax_rate = a.tax_rate
        c.tax_exempt = a.tax_exempt
        c.save(update_fields=[
            "account_terms", "credit_limit", "credit_status",
            "tax_rate", "tax_exempt",
        ])


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_customer_closed_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("account_terms", models.CharField(blank=True, max_length=50)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "credit_status",
                    models.CharField(
                        choices=[("Good", "Good"), ("Fair", "Fair"), ("Poor", "Poor")],
                        default="Good",
                        max_length=10,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("tax_exempt", models.BooleanField(default=False)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "crm_account",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "credit_status"],
                        name="crm_account_tenant__6267ae_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(
            copy_customer_billing_to_account,
            reverse_copy_account_to_customer,
        ),
        migrations.RemoveField(
            model_name="customer",
            name="account_terms",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="credit_limit",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="credit_status",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tax_exempt",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tax_rate",
        ),
    ]
