# Generated by Django 6.0.4 on 2026-05-03 19:35

import config.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_customer_inactive_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="account",
            name="po_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="pricing_tier",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="access_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="annual_revenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="dba",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="customer",
            name="display_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="customer",
            name="do_not_call",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="do_not_contact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="do_not_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="do_not_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="ein",
            field=config.fields.EncryptedCharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="employee_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="legal_entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LLC", "LLC"),
                    ("Corp", "Corporation"),
                    ("Partnership", "Partnership"),
                    ("SoleProp", "Sole Proprietorship"),
                    ("NonProfit", "Non-Profit"),
                    ("Government", "Government"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="marketing_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="portal_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_portal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("SMS", "SMS"),
                    ("Mail", "Mail"),
                    ("None", "None"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="preferred_language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="preferred_service_window",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Morning", "Morning"),
                    ("Afternoon", "Afternoon"),
                    ("Evening", "Evening"),
                    ("Anytime", "Anytime"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="preferred_technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_by_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="primary_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_customers",
                to="crm.person",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="requires_appointment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="service_route",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="service_zone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="source_system",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_id",
            field=config.fields.EncryptedCharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="vat_number",
            field=config.fields.EncryptedCharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant_id", "industry"], name="crm_custome_tenant__9f40ca_idx"
            ),
        ),
    ]
