# Generated by Django 6.0.4 on 2026-05-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0007_customer_field_expansion"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="What this person prefers to be called (display alternative to first_name).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="prefix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mr", "Mr"),
                    ("Mrs", "Mrs"),
                    ("Ms", "Ms"),
                    ("Mx", "Mx"),
                    ("Dr", "Dr"),
                    ("Prof", "Prof"),
                    ("Rev", "Rev"),
                    ("Other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="suffix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Jr", "Jr"),
                    ("Sr", "Sr"),
                    ("II", "II"),
                    ("III", "III"),
                    ("IV", "IV"),
                    ("PhD", "PhD"),
                    ("MD", "MD"),
                    ("Esq", "Esq"),
                    ("Other", "Other"),
                ],
                max_length=10,
            ),
        ),
    ]
