# Generated by Django 6.0.4 on 2026-05-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0008_person_expansion"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country_code",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-2 country code (US, GB, CA).",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="geocoded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Address has been validated against an authoritative source (USPS, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="state_code",
            field=models.CharField(
                blank=True,
                help_text="State/region abbreviation (CA, NY, TX). For dispatch routing.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="street_2",
            field=models.CharField(
                blank=True,
                help_text="Apt/Suite/Floor — second address line.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="country_code",
            field=models.CharField(
                blank=True,
                help_text="International dialing code, including '+' (e.g. '+1', '+44').",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Number has been verified (e.g., SMS code)."
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="sms_capable",
            field=models.BooleanField(
                default=False,
                help_text="Whether this number can receive SMS. Independent of phone_type.",
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
