# Generated by Django 6.0.4 on 2026-05-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0009_address_phone_hardening"),
        ("procurement", "0003_vendor_account_split"),
        ("service", "0003_workorder_total_amount_alter_workorder_actual_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_billing_contact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_decision_maker",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_emergency_contact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_technical_contact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_contacted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent successful outbound contact (call, email, meeting).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="crm.contact",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["tenant_id", "customer_id", "is_primary"],
                name="crm_contact_tenant__d2f509_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["tenant_id", "reports_to_id"],
                name="crm_contact_tenant__c4b7eb_idx",
            ),
        ),
    ]
