# Generated by Django 6.0.4 on 2026-05-03

import django.db.models.deletion
from django.db import migrations, models


def backfill_lead_relations(apps, schema_editor):
    """Backfill Lead.person and Lead.customer for existing rows.

    For each Lead:
      * Create a Person from first_name / last_name → link as lead.person
      * If lead.customer is null, create a Residential Customer with the new
        Person as primary_person → link as lead.customer
      * If lead.phone: create Phone row with customer=lead.customer
      * If lead.email: create Social row (type='Email') with customer=lead.customer
      * If lead.notes: create Note row with lead=lead, body=notes

    Uses raw historical models (no live signals fire), so we also explicitly
    create the Customer's Account record (normally auto-created by signal).
    """
    Lead = apps.get_model("crm", "Lead")
    Person = apps.get_model("crm", "Person")
    Customer = apps.get_model("crm", "Customer")
    Account = apps.get_model("crm", "Account")
    Phone = apps.get_model("crm", "Phone")
    Social = apps.get_model("crm", "Social")
    Note = apps.get_model("notes", "Note")

    for lead in Lead.objects.all():
        # Person
        person = Person.objects.create(
            tenant_id=lead.tenant_id,
            first_name=lead.first_name or 'Unknown',
            last_name=lead.last_name or 'Lead',
            created_by=lead.created_by,
        )
        lead.person = person

        # Customer (auto-create if missing)
        if lead.customer_id is None:
            customer = Customer.objects.create(
                tenant_id=lead.tenant_id,
                account_type='Residential',  # default for migrated rows
                company_name=lead.company_name or '',
                primary_person=person,
                assigned_to=lead.assigned_to,
                created_by=lead.created_by,
            )
            # Account is normally auto-created by post_save signal. Historical
            # models don't fire the live signal, so create it explicitly.
            Account.objects.create(
                tenant_id=customer.tenant_id,
                customer=customer,
                created_by=customer.created_by,
            )
            lead.customer = customer

        # Phone
        if lead.phone:
            Phone.objects.create(
                tenant_id=lead.tenant_id,
                customer=lead.customer,
                phone_type='Mobile',
                number=lead.phone,
                created_by=lead.created_by,
            )

        # Email → Social
        if lead.email:
            Social.objects.create(
                tenant_id=lead.tenant_id,
                customer=lead.customer,
                type='Email',
                value=lead.email,
                created_by=lead.created_by,
            )

        # Notes → Note (ExclusiveArc with lead FK)
        if lead.notes:
            Note.objects.create(
                tenant_id=lead.tenant_id,
                lead=lead,
                body=lead.notes,
                created_by=lead.created_by,
            )

        lead.save(update_fields=['person', 'customer'])


def reverse_backfill_lead_relations(apps, schema_editor):
    """Best-effort reverse: copy person.first_name/last_name back into Lead.
    Phones/Socials/Notes are NOT moved back — they could have been edited or
    are referenced elsewhere; the data stays where it is."""
    Lead = apps.get_model("crm", "Lead")
    for lead in Lead.objects.select_related("person").all():
        if lead.person:
            lead.first_name = lead.person.first_name or ''
            lead.last_name = lead.person.last_name or ''
            lead.save(update_fields=['first_name', 'last_name'])


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0011_lead_opportunity_expansion"),
        ("notes", "0001_initial"),
    ]

    operations = [
        # 1. Add `person` as nullable so we can backfill it.
        migrations.AddField(
            model_name="lead",
            name="person",
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="crm.person",
            ),
        ),
        # 2. Backfill: create Person for every Lead, create Customer if
        # missing, migrate phone/email/notes into the proper bridges.
        migrations.RunPython(
            backfill_lead_relations,
            reverse_backfill_lead_relations,
        ),
        # 3. Tighten person to non-null + PROTECT.
        migrations.AlterField(
            model_name="lead",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="crm.person",
            ),
        ),
        # 4. Tighten customer to non-null + PROTECT (was nullable SET_NULL).
        migrations.AlterField(
            model_name="lead",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="crm.customer",
            ),
        ),
        # 5. Drop the denormalized fields now that data lives elsewhere.
        migrations.RemoveField(model_name="lead", name="first_name"),
        migrations.RemoveField(model_name="lead", name="last_name"),
        migrations.RemoveField(model_name="lead", name="company_name"),
        migrations.RemoveField(model_name="lead", name="phone"),
        migrations.RemoveField(model_name="lead", name="email"),
        migrations.RemoveField(model_name="lead", name="notes"),
        # 6. New index for the customer FK.
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant_id", "customer_id"],
                name="crm_lead_tenant__cust_idx",
            ),
        ),
    ]
