# Generated by Django 5.0.1 on 2026-01-11 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity that owns this file (e.g., 'client', 'invoice')",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(help_text="UUID of entity that owns this file"),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename as uploaded", max_length=500
                    ),
                ),
                (
                    "stored_filename",
                    models.CharField(
                        help_text="Stored filename (UUID + sanitized original)",
                        max_length=500,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="MIME type of file (e.g., 'application/pdf')",
                        max_length=100,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "storage_path",
                    models.CharField(
                        help_text="Relative storage path from storage root",
                        max_length=1000,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of file"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 checksum for integrity verification (Pro only)",
                        max_length=64,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileUploadLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type being uploaded to", max_length=50
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(help_text="Entity ID being uploaded to"),
                ),
                (
                    "original_filename",
                    models.CharField(help_text="Filename from upload", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="success",
                        help_text="Upload success/failure status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if upload failed"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        help_text="The file that was uploaded (null if failed)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_logs",
                        to="files.storedfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileDownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When file was downloaded"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type the download was for", max_length=50
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(help_text="Entity ID the download was for"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address (optional)", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who downloaded the file",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="File that was downloaded",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="download_logs",
                        to="files.storedfile",
                    ),
                ),
            ],
            options={
                "permissions": [],
            },
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["entity_type"], name="files_store_entity__4b2786_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="files_store_entity__81c314_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["created_at"], name="files_store_created_5279db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadlog",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="files_fileu_entity__4aa826_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadlog",
            index=models.Index(
                fields=["created_at"], name="files_fileu_created_8b0c86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileuploadlog",
            index=models.Index(fields=["status"], name="files_fileu_status_da059d_idx"),
        ),
        migrations.AddIndex(
            model_name="filedownloadlog",
            index=models.Index(fields=["file"], name="files_filed_file_id_b0fe06_idx"),
        ),
        migrations.AddIndex(
            model_name="filedownloadlog",
            index=models.Index(fields=["user"], name="files_filed_user_id_007f02_idx"),
        ),
        migrations.AddIndex(
            model_name="filedownloadlog",
            index=models.Index(
                fields=["timestamp"], name="files_filed_timesta_8d509d_idx"
            ),
        ),
    ]
