# Generated by Django 5.2.12 on 2026-03-24 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('default_duration_months', models.PositiveSmallIntegerField(default=12)),
                ('terms', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'maintenance_agreement',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='maintenance_tenant__bb7f09_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('asset_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired'), ('Sold', 'Sold')], default='Active', max_length=10)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='crm.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assets', to='crm.customer')),
            ],
            options={
                'db_table': 'maintenance_asset',
            },
        ),
        migrations.CreateModel(
            name='CustomerAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Active', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_agreements', to='maintenance.agreement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agreements', to='crm.customer')),
            ],
            options={
                'db_table': 'maintenance_customeragreement',
            },
        ),
        migrations.CreateModel(
            name='PreventativeMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual'), ('As Needed', 'As Needed')], default='Monthly', max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('last_performed_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_schedules', to='maintenance.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_preventativemaintenance',
            },
        ),
        migrations.CreateModel(
            name='SubAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired')], default='Active', max_length=10)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_assets', to='maintenance.asset')),
            ],
            options={
                'db_table': 'maintenance_subasset',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant_id', 'customer_id'], name='maintenance_tenant__3963ad_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant_id', 'status'], name='maintenance_tenant__6f9f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='customeragreement',
            index=models.Index(fields=['tenant_id', 'customer_id'], name='maintenance_tenant__dd3772_idx'),
        ),
        migrations.AddIndex(
            model_name='customeragreement',
            index=models.Index(fields=['tenant_id', 'status'], name='maintenance_tenant__998223_idx'),
        ),
        migrations.AddIndex(
            model_name='preventativemaintenance',
            index=models.Index(fields=['tenant_id', 'asset_id'], name='maintenance_tenant__c575f9_idx'),
        ),
        migrations.AddIndex(
            model_name='preventativemaintenance',
            index=models.Index(fields=['tenant_id', 'next_due_date'], name='maintenance_tenant__76c63a_idx'),
        ),
        migrations.AddIndex(
            model_name='subasset',
            index=models.Index(fields=['tenant_id', 'asset_id'], name='maintenance_tenant__a0c911_idx'),
        ),
    ]
