# Generated by Django 6.0.3 on 2026-04-05 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValueList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable list name, e.g. "Lead Sources".',
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='Machine identifier for code reference, e.g. "lead_source".',
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="True for system-seeded lists created at provisioning.",
                    ),
                ),
            ],
            options={
                "db_table": "value_lists_valuelist",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "slug"],
                        name="value_lists_tenant__30b260_idx",
                    )
                ],
                "unique_together": {("tenant_id", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ValueListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Display text shown in UI dropdowns.", max_length=255
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Stored value in referencing model fields.",
                        max_length=255,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Display ordering in dropdowns (ascending).",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="If True, pre-selected in new records."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive items hidden from new selections.",
                    ),
                ),
                (
                    "value_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="value_lists.valuelist",
                    ),
                ),
            ],
            options={
                "db_table": "value_lists_valuelistitem",
                "ordering": ["sort_order", "label"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "value_list_id"],
                        name="value_lists_tenant__fc64b2_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "value_list_id", "is_active"],
                        name="value_lists_tenant__73e09a_idx",
                    ),
                ],
                "unique_together": {("tenant_id", "value_list", "value")},
            },
        ),
    ]
