# Generated by Django 6.0.3 on 2026-04-05 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NumberingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Machine key (e.g. customer, work_order, service_request)",
                        max_length=50,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "prefix",
                    models.CharField(help_text="e.g. C, W, I, SR, YU", max_length=20),
                ),
                ("include_year", models.BooleanField(default=True)),
                (
                    "year_format",
                    models.CharField(
                        choices=[("YY", "YY"), ("YYYY", "YYYY")],
                        default="YY",
                        max_length=4,
                    ),
                ),
                ("include_month", models.BooleanField(default=False)),
                ("sequence_length", models.PositiveIntegerField(default=4)),
                ("delimiter", models.CharField(default="-", max_length=5)),
                (
                    "reset_behavior",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                        ],
                        default="yearly",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "numbering_numberingrule",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type"],
                        name="numbering_n_tenant__ab7f74_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "is_enabled"],
                        name="numbering_n_tenant__66f122_idx",
                    ),
                ],
                "unique_together": {("tenant_id", "entity_type")},
            },
        ),
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("current_value", models.PositiveIntegerField(default=0)),
                ("last_reset_date", models.DateField(blank=True, null=True)),
                (
                    "rule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence",
                        to="numbering.numberingrule",
                    ),
                ),
            ],
            options={
                "db_table": "numbering_numbersequence",
            },
        ),
        migrations.CreateModel(
            name="AssignedNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Denormalized from rule for fast queries",
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("number", models.CharField(max_length=100)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.CharField(
                        help_text='User email or "System"', max_length=200
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="numbering.numberingrule",
                    ),
                ),
            ],
            options={
                "db_table": "numbering_assignednumber",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type"],
                        name="numbering_a_tenant__bb3952_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "entity_id"],
                        name="numbering_a_tenant__82ae2d_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "number"],
                        name="numbering_a_tenant__ef9a71_idx",
                    ),
                    models.Index(
                        fields=["assigned_at"], name="numbering_a_assigne_bce5d4_idx"
                    ),
                ],
                "unique_together": {
                    ("tenant_id", "entity_type", "entity_id"),
                    ("tenant_id", "entity_type", "number"),
                },
            },
        ),
    ]
