# Generated by Django 5.0.1 on 2026-02-10 02:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        editable=False,
                        help_text="Unique system-generated account number (ACYYNNN).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Business Name or Display Name.", max_length=255
                    ),
                ),
                (
                    "date_started",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the relationship started (defaults to today, editable).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Active",
                        help_text="Lifecycle status (e.g., Prospect, Active). Controlled by Value List.",
                        max_length=50,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        help_text="Classification (e.g., Commercial, Residential). Controlled by Value List.",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["account_number"], name="clients_cli_account_95041b_idx"
                    ),
                    models.Index(fields=["name"], name="clients_cli_name_5ab7bc_idx"),
                    models.Index(
                        fields=["status"], name="clients_cli_status_ce0d15_idx"
                    ),
                ],
            },
        ),
    ]
