# Generated by Django 5.2.12 on 2026-03-24 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('Van', 'Van'), ('Truck', 'Truck'), ('Car', 'Car'), ('Trailer', 'Trailer'), ('Heavy Equipment', 'Heavy Equipment'), ('Other', 'Other')], default='Van', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Service', 'In Service'), ('Out of Service', 'Out of Service'), ('Retired', 'Retired')], default='Active', max_length=15)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'fleet_vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehicleInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'fleet_vehicleinventory',
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=10)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('mileage_at_service', models.PositiveIntegerField(blank=True, null=True)),
                ('next_service_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, help_text='Vendor name or internal user description.', max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'fleet_vehiclemaintenance',
            },
        ),
        migrations.CreateModel(
            name='MileageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('log_date', models.DateField()),
                ('odometer_start', models.PositiveIntegerField(default=0)),
                ('odometer_end', models.PositiveIntegerField(default=0)),
                ('miles_driven', models.PositiveIntegerField(default=0)),
                ('purpose', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fleet_mileagelog',
            },
        ),
    ]
