# Generated by Django 5.2.12 on 2026-03-24 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('inventory', '0003_inventoryitem_and_more'),
        ('service', '0001_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mileagelog',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_logs', to='service.workorder'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='workforce.workgroup'),
        ),
        migrations.AddField(
            model_name='mileagelog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_logs', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicle_inventory', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='vehicleinventory',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_inventory', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['tenant_id', 'status'], name='fleet_vehic_tenant__6f675a_idx'),
        ),
        migrations.AddIndex(
            model_name='mileagelog',
            index=models.Index(fields=['tenant_id', 'vehicle_id'], name='fleet_milea_tenant__b91793_idx'),
        ),
        migrations.AddIndex(
            model_name='mileagelog',
            index=models.Index(fields=['tenant_id', 'log_date'], name='fleet_milea_tenant__ff6ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinventory',
            index=models.Index(fields=['tenant_id', 'vehicle_id'], name='fleet_vehic_tenant__e7daca_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinventory',
            index=models.Index(fields=['tenant_id', 'product_id'], name='fleet_vehic_tenant__b6f464_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemaintenance',
            index=models.Index(fields=['tenant_id', 'vehicle_id'], name='fleet_vehic_tenant__d04f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemaintenance',
            index=models.Index(fields=['tenant_id', 'status'], name='fleet_vehic_tenant__e9027c_idx'),
        ),
    ]
