# Generated by Django 6.0.3 on 2026-04-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0002_initial"),
        ("inventory", "0003_inventoryitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleinventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="vehicle_inventory",
                to="inventory.inventoryitem",
            ),
        ),
    ]
