# Generated by Django 5.0.1 on 2026-01-10 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique value list identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Purpose and usage of this value list"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Value List",
                "verbose_name_plural": "Value Lists",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ValueListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Actual value stored/used in code", max_length=100
                    ),
                ),
                (
                    "display_label",
                    models.CharField(help_text="User-visible label", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "value_list",
                    models.ForeignKey(
                        help_text="Parent value list",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.valuelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Value List Item",
                "verbose_name_plural": "Value List Items",
                "ordering": ["value_list", "sort_order", "display_label"],
            },
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique configuration key",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Purpose and usage of this preference"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("path", "File/Directory Path"),
                        ],
                        help_text="Data type for type enforcement",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Current value (stored as text, cast by application)"
                    ),
                ),
                ("default_value", models.TextField(help_text="Default value")),
                (
                    "is_editable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this preference can be edited by administrators",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preference",
                "verbose_name_plural": "Preferences",
                "ordering": ["key"],
                "indexes": [
                    models.Index(fields=["key"], name="core_prefer_key_81a656_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="valuelist",
            index=models.Index(fields=["key"], name="core_valuel_key_b07a55_idx"),
        ),
        migrations.AddIndex(
            model_name="valuelistitem",
            index=models.Index(
                fields=["value_list", "is_active"],
                name="core_valuel_value_l_d6b5a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="valuelistitem",
            index=models.Index(
                fields=["value_list", "sort_order"],
                name="core_valuel_value_l_52e99f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="valuelistitem",
            unique_together={("value_list", "value")},
        ),
    ]
