# Generated by Django 5.0.1 on 2026-02-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("path", "File/Directory Path"),
                    ("password", "Password"),
                ],
                help_text="Data type for type enforcement",
                max_length=20,
            ),
        ),
    ]
