# Generated by Django 5.0.1 on 2026-02-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_preference_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="input_type",
            field=models.CharField(
                blank=True,
                help_text="Specific UI widget hints (color, file, etc.)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="If True, value cannot be changed by users (system process only)",
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="is_secret",
            field=models.BooleanField(
                default=False, help_text="If True, value is masked in UI"
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="preference_group",
            field=models.CharField(
                default="General",
                help_text="Logical grouping for UI display",
                max_length=50,
            ),
        ),
    ]
