# Generated by Django 6.0.3 on 2026-04-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_inventoryitem_and_more"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deposit_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deposit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Percentage", "Percentage"),
                    ("Fixed Amount", "Fixed Amount"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recurrence_pattern",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="invoice",
            name="stripe_payment_link_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("On Hold", "On Hold"),
                    ("Partially Applied", "Partially Applied"),
                    ("Applied", "Applied"),
                    ("Paid", "Paid"),
                    ("Returned", "Returned"),
                    ("Voided", "Voided"),
                    ("Refunded", "Refunded"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="customer_facing_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="hold_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="hold_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="recurrence_pattern",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_lines",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="quoteline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_lines",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="workorderline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_order_lines",
                to="inventory.inventoryitem",
            ),
        ),
    ]
