# Generated by Django 6.0.3 on 2026-04-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_invoice_deposit_amount_invoice_deposit_applied_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="actual_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
