# Generated by Django 6.0.3 on 2026-04-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="InventoryItem",
        ),
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_p_tenant__79df85_idx",
        ),
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_p_tenant__ed1c40_idx",
        ),
        migrations.AlterField(
            model_name="invpricehistory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="kititem",
            name="kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_items",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="kititem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="included_in_kits",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="pricebookentry",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricebook_entries",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["tenant_id", "status"], name="inventory_p_tenant__79df85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["tenant_id", "type"], name="inventory_p_tenant__ed1c40_idx"
            ),
        ),
    ]
