# Generated by Django 5.0.1 on 2026-01-11 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type this rule applies to (e.g., 'invoice')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether numbering is active for this entity",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Static prefix (e.g., 'INV', 'WO')",
                        max_length=50,
                    ),
                ),
                (
                    "include_year",
                    models.BooleanField(
                        default=False, help_text="Include YYYY in number format"
                    ),
                ),
                (
                    "include_month",
                    models.BooleanField(
                        default=False, help_text="Include MM in number format"
                    ),
                ),
                (
                    "sequence_length",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Length of numeric sequence part (padded with zeros)",
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        default="-",
                        help_text="Delimiter between format components",
                        max_length=5,
                    ),
                ),
                (
                    "reset_behavior",
                    models.CharField(
                        choices=[
                            ("none", "No Reset"),
                            ("yearly", "Reset Each Year"),
                            ("monthly", "Reset Each Month"),
                        ],
                        default="none",
                        help_text="When to reset sequence (yearly, monthly, or never)",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this numbering rule"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignedNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity assigned this number", max_length=50
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(help_text="UUID of entity assigned this number"),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="The generated human-readable number", max_length=100
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this number was assigned"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="User/system that triggered the assignment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_numbers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="The numbering rule used to generate this number",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_numbers",
                        to="numbering.numberingrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current sequence counter (incremented with each assignment)",
                    ),
                ),
                (
                    "last_reset_date",
                    models.DateField(
                        blank=True, help_text="Date sequence was last reset", null=True
                    ),
                ),
                (
                    "rule",
                    models.OneToOneField(
                        help_text="The numbering rule this sequence belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence",
                        to="numbering.numberingrule",
                    ),
                ),
            ],
            options={
                "permissions": [],
            },
        ),
        migrations.AddIndex(
            model_name="numberingrule",
            index=models.Index(
                fields=["entity_type"], name="numbering_n_entity__1fe9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="numberingrule",
            index=models.Index(
                fields=["is_enabled"], name="numbering_n_is_enab_63c090_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignednumber",
            index=models.Index(
                fields=["entity_type"], name="numbering_a_entity__dddd71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignednumber",
            index=models.Index(
                fields=["entity_id"], name="numbering_a_entity__bf3a05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignednumber",
            index=models.Index(fields=["number"], name="numbering_a_number_6926cb_idx"),
        ),
        migrations.AddIndex(
            model_name="assignednumber",
            index=models.Index(
                fields=["assigned_at"], name="numbering_a_assigne_bce5d4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignednumber",
            constraint=models.UniqueConstraint(
                fields=("entity_type", "number"), name="unique_number_per_entity_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignednumber",
            constraint=models.UniqueConstraint(
                fields=("entity_type", "entity_id"), name="unique_entity_assignment"
            ),
        ),
    ]
