# Generated by Django 5.0.1 on 2026-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numbering", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="numberingrule",
            name="year_format",
            field=models.CharField(
                choices=[("YYYY", "Full Year (2026)"), ("YY", "Short Year (26)")],
                default="YYYY",
                help_text="Year format if include_year is True",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="numberingrule",
            name="include_year",
            field=models.BooleanField(
                default=False, help_text="Include year in number format"
            ),
        ),
    ]
