# Generated by Django 5.0.1 on 2026-02-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numbering", "0002_numberingrule_year_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="numberingrule",
            name="custom_format",
            field=models.CharField(
                blank=True,
                help_text="Custom formatter function name (e.g., 'alpha_year')",
                max_length=50,
                null=True,
            ),
        ),
    ]
