# Generated by Django 5.0.1 on 2026-02-14 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("numbering", "0003_numberingrule_custom_format"),
    ]

    def update_client_rule(apps, schema_editor):
        NumberingRule = apps.get_model('numbering', 'NumberingRule')
        try:
            # Update 'client' rule which is the one actually used by code
            rule = NumberingRule.objects.get(entity_type='client')
            rule.prefix = 'AC'
            rule.delimiter = ''
            rule.include_year = True
            rule.year_format = 'YY'
            rule.sequence_length = 3
            # rule.reset_behavior = 'yearly' # Keeping default 'none' as discussed to be safe with sequence
            rule.save()
            
            # Disable 'clients' rule if it exists to avoid confusion
            NumberingRule.objects.filter(entity_type='clients').update(is_enabled=False)
            
        except NumberingRule.DoesNotExist:
            pass

    operations = [
        migrations.RunPython(update_client_rule),
    ]
