# Generated by Django 5.0.1 on 2026-01-20 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "backup_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique backup identifier (timestamp-based)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "backup_path",
                    models.CharField(
                        help_text="Absolute path to backup folder", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        help_text="Current backup status",
                        max_length=20,
                    ),
                ),
                (
                    "backup_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When backup was created"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, help_text="When backup process started", null=True
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="When backup process completed", null=True
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, help_text="BrixaWares version", max_length=50
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        blank=True, help_text="Database schema version", max_length=50
                    ),
                ),
                (
                    "database_version",
                    models.CharField(
                        blank=True,
                        help_text="PostgreSQL/database version",
                        max_length=50,
                    ),
                ),
                (
                    "install_mode",
                    models.CharField(
                        choices=[("solo", "Solo"), ("multi", "Multi-user")],
                        default="solo",
                        help_text="Installation mode at time of backup",
                        max_length=20,
                    ),
                ),
                (
                    "database_size_bytes",
                    models.BigIntegerField(
                        default=0, help_text="Size of database dump in bytes"
                    ),
                ),
                (
                    "files_size_bytes",
                    models.BigIntegerField(
                        default=0, help_text="Size of files archive in bytes"
                    ),
                ),
                (
                    "file_count",
                    models.IntegerField(
                        default=0, help_text="Number of files/documents backed up"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, help_text="Human-readable reason for backup failure"
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                            ("pre_upgrade", "Pre-Upgrade"),
                        ],
                        default="scheduled",
                        help_text="Type of backup (automatic, manual, pre-upgrade)",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-backup_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("backup", "Backup"),
                            ("restore", "Restore"),
                            ("verify", "Verify"),
                            ("cleanup", "Cleanup"),
                            ("schedule_check", "Schedule Check"),
                        ],
                        help_text="Type of backup operation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("info", "Info"),
                        ],
                        default="info",
                        help_text="Operation result status",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Detailed operation message/error"
                    ),
                ),
                (
                    "log_timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When operation was logged",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Operation duration in seconds", null=True
                    ),
                ),
                (
                    "initiated_by",
                    models.CharField(
                        default="system",
                        help_text="Who/what initiated (username or 'system')",
                        max_length=255,
                    ),
                ),
                (
                    "backup",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related backup (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="backup.backup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-log_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BackupSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created (set once, never changes)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Operational flag for disabling records without deleting them",
                    ),
                ),
                (
                    "backup_path",
                    models.CharField(
                        default="C:\\ProgramData\\BrixaWares\\Backups",
                        help_text="Absolute path where backups are stored. Must be writable.",
                        max_length=500,
                    ),
                ),
                (
                    "schedule_time",
                    models.TimeField(
                        default="02:00",
                        help_text="Time of day (local) when automatic backup runs (HH:MM)",
                    ),
                ),
                (
                    "retention_count",
                    models.IntegerField(
                        default=10, help_text="Number of backups to keep (minimum 5)"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable/disable automatic backups"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Backup Settings",
            },
        ),
        migrations.AddIndex(
            model_name="backup",
            index=models.Index(
                fields=["-backup_timestamp"], name="backup_back_backup__944271_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backup",
            index=models.Index(fields=["status"], name="backup_back_status_65f323_idx"),
        ),
        migrations.AddIndex(
            model_name="backuplog",
            index=models.Index(
                fields=["-log_timestamp"], name="backup_back_log_tim_1b56f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backuplog",
            index=models.Index(
                fields=["operation", "-log_timestamp"],
                name="backup_back_operati_ffe891_idx",
            ),
        ),
    ]
